//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 05:57:43 PM CET 
//


package mx.randalf.converterxls2xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="default" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="colonna">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>nonNegativeInteger">
 *                 &lt;attGroup ref="{http://www.randalf.mx/converterXls2Xml}gFormat"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="campo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://www.randalf.mx/converterXls2Xml}gFormat"/>
 *                 &lt;attribute name="tipo" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="numPagina"/>
 *                       &lt;enumeration value="rectoVerso"/>
 *                       &lt;enumeration value="numPaginaRomano"/>
 *                       &lt;enumeration value="cronaca"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "_default",
    "colonna",
    "campo"
})
@XmlRootElement(name = "dati")
public class Dati {

    @XmlElement(name = "default")
    protected String _default;
    protected Dati.Colonna colonna;
    protected Dati.Campo campo;

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefault(String value) {
        this._default = value;
    }

    /**
     * Gets the value of the colonna property.
     * 
     * @return
     *     possible object is
     *     {@link Dati.Colonna }
     *     
     */
    public Dati.Colonna getColonna() {
        return colonna;
    }

    /**
     * Sets the value of the colonna property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dati.Colonna }
     *     
     */
    public void setColonna(Dati.Colonna value) {
        this.colonna = value;
    }

    /**
     * Gets the value of the campo property.
     * 
     * @return
     *     possible object is
     *     {@link Dati.Campo }
     *     
     */
    public Dati.Campo getCampo() {
        return campo;
    }

    /**
     * Sets the value of the campo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dati.Campo }
     *     
     */
    public void setCampo(Dati.Campo value) {
        this.campo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.randalf.mx/converterXls2Xml}gFormat"/>
     *       &lt;attribute name="tipo" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="numPagina"/>
     *             &lt;enumeration value="rectoVerso"/>
     *             &lt;enumeration value="numPaginaRomano"/>
     *             &lt;enumeration value="cronaca"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Campo {

        @XmlAttribute(name = "tipo", required = true)
        protected String tipo;
        @XmlAttribute(name = "decimalFormat")
        protected String decimalFormat;
        @XmlAttribute(name = "converter")
        protected String converter;
        @XmlAttribute(name = "prefix")
        protected String prefix;
        @XmlAttribute(name = "suffix")
        protected String suffix;

        /**
         * Gets the value of the tipo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipo(String value) {
            this.tipo = value;
        }

        /**
         * Gets the value of the decimalFormat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecimalFormat() {
            return decimalFormat;
        }

        /**
         * Sets the value of the decimalFormat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecimalFormat(String value) {
            this.decimalFormat = value;
        }

        /**
         * Gets the value of the converter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConverter() {
            return converter;
        }

        /**
         * Sets the value of the converter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConverter(String value) {
            this.converter = value;
        }

        /**
         * Gets the value of the prefix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrefix() {
            return prefix;
        }

        /**
         * Sets the value of the prefix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrefix(String value) {
            this.prefix = value;
        }

        /**
         * Gets the value of the suffix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuffix() {
            return suffix;
        }

        /**
         * Sets the value of the suffix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuffix(String value) {
            this.suffix = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>nonNegativeInteger">
     *       &lt;attGroup ref="{http://www.randalf.mx/converterXls2Xml}gFormat"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Colonna {

        @XmlValue
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger value;
        @XmlAttribute(name = "decimalFormat")
        protected String decimalFormat;
        @XmlAttribute(name = "converter")
        protected String converter;
        @XmlAttribute(name = "prefix")
        protected String prefix;
        @XmlAttribute(name = "suffix")
        protected String suffix;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the decimalFormat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecimalFormat() {
            return decimalFormat;
        }

        /**
         * Sets the value of the decimalFormat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecimalFormat(String value) {
            this.decimalFormat = value;
        }

        /**
         * Gets the value of the converter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConverter() {
            return converter;
        }

        /**
         * Sets the value of the converter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConverter(String value) {
            this.converter = value;
        }

        /**
         * Gets the value of the prefix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrefix() {
            return prefix;
        }

        /**
         * Sets the value of the prefix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrefix(String value) {
            this.prefix = value;
        }

        /**
         * Gets the value of the suffix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuffix() {
            return suffix;
        }

        /**
         * Sets the value of the suffix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuffix(String value) {
            this.suffix = value;
        }

    }

}
