//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 05:57:43 PM CET 
//


package mx.randalf.converterxls2xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="formatoFile">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="tipo" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="xls"/>
 *                       &lt;enumeration value="csv"/>
 *                       &lt;enumeration value="tsv"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="primaRiga" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.randalf.mx/converterXls2Xml}path"/>
 *         &lt;element name="image">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.randalf.mx/converterXls2Xml}path"/>
 *                   &lt;element ref="{http://www.randalf.mx/converterXls2Xml}formatoImg"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "formatoFile",
    "path",
    "image"
})
@XmlRootElement(name = "input")
public class Input {

    @XmlElement(required = true)
    protected Input.FormatoFile formatoFile;
    @XmlElement(required = true)
    protected String path;
    @XmlElement(required = true)
    protected Input.Image image;

    /**
     * Gets the value of the formatoFile property.
     * 
     * @return
     *     possible object is
     *     {@link Input.FormatoFile }
     *     
     */
    public Input.FormatoFile getFormatoFile() {
        return formatoFile;
    }

    /**
     * Sets the value of the formatoFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Input.FormatoFile }
     *     
     */
    public void setFormatoFile(Input.FormatoFile value) {
        this.formatoFile = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link Input.Image }
     *     
     */
    public Input.Image getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link Input.Image }
     *     
     */
    public void setImage(Input.Image value) {
        this.image = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="tipo" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="xls"/>
     *             &lt;enumeration value="csv"/>
     *             &lt;enumeration value="tsv"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="primaRiga" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FormatoFile {

        @XmlAttribute(name = "tipo", required = true)
        protected String tipo;
        @XmlAttribute(name = "primaRiga")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger primaRiga;

        /**
         * Gets the value of the tipo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipo(String value) {
            this.tipo = value;
        }

        /**
         * Gets the value of the primaRiga property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPrimaRiga() {
            if (primaRiga == null) {
                return new BigInteger("0");
            } else {
                return primaRiga;
            }
        }

        /**
         * Sets the value of the primaRiga property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPrimaRiga(BigInteger value) {
            this.primaRiga = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.randalf.mx/converterXls2Xml}path"/>
     *         &lt;element ref="{http://www.randalf.mx/converterXls2Xml}formatoImg"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "path",
        "formatoImg"
    })
    public static class Image {

        @XmlElement(required = true)
        protected String path;
        @XmlElement(required = true)
        protected FormatoImg formatoImg;

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

        /**
         * Gets the value of the formatoImg property.
         * 
         * @return
         *     possible object is
         *     {@link FormatoImg }
         *     
         */
        public FormatoImg getFormatoImg() {
            return formatoImg;
        }

        /**
         * Sets the value of the formatoImg property.
         * 
         * @param value
         *     allowed object is
         *     {@link FormatoImg }
         *     
         */
        public void setFormatoImg(FormatoImg value) {
            this.formatoImg = value;
        }

    }

}
