//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 05:57:43 PM CET 
//


package mx.randalf.converterxls2xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="typeFileOutput">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="mag"/>
 *               &lt;enumeration value="mets"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.randalf.mx/converterXls2Xml}path"/>
 *         &lt;element name="cartella" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="gen">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="stprog" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="collection" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="agency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="access_rights">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;pattern value="0"/>
 *                         &lt;pattern value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="completeness">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;pattern value="0"/>
 *                         &lt;pattern value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="bib">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="key">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;sequence maxOccurs="unbounded">
 *                     &lt;element name="campo">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati" maxOccurs="unbounded"/>
 *                             &lt;/sequence>
 *                             &lt;attribute name="tipo" use="required">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="bid"/>
 *                                   &lt;enumeration value="natura"/>
 *                                   &lt;enumeration value="autore"/>
 *                                   &lt;enumeration value="titolo"/>
 *                                   &lt;enumeration value="pubblicazione"/>
 *                                   &lt;enumeration value="biblioteca"/>
 *                                   &lt;enumeration value="collocazione"/>
 *                                   &lt;enumeration value="inventario"/>
 *                                   &lt;enumeration value="annata"/>
 *                                   &lt;enumeration value="numero"/>
 *                                   &lt;enumeration value="giorno"/>
 *                                   &lt;enumeration value="mese"/>
 *                                   &lt;enumeration value="anno"/>
 *                                   &lt;enumeration value="cronaca"/>
 *                                   &lt;enumeration value="year"/>
 *                                   &lt;enumeration value="issue"/>
 *                                   &lt;enumeration value="stpiece_per"/>
 *                                   &lt;enumeration value="part_number"/>
 *                                   &lt;enumeration value="part_name"/>
 *                                   &lt;enumeration value="stpiece_vol"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/attribute>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="xml">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="folder" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded">
 *                             &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="fileName">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded">
 *                             &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="extension" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="images">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nomenclatura">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="image" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.randalf.mx/converterXls2Xml}path"/>
 *                             &lt;element ref="{http://www.randalf.mx/converterXls2Xml}formatoImg"/>
 *                             &lt;element name="usage">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="1"/>
 *                                   &lt;enumeration value="2"/>
 *                                   &lt;enumeration value="3"/>
 *                                   &lt;enumeration value="4"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="converter" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ppi" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="quality" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="resize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="pagine">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                     &lt;element name="stop" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="pagina" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;/choice>
 *         &lt;element name="pagInizio" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "typeFileOutput",
    "path",
    "cartella",
    "gen",
    "bib",
    "xml",
    "images",
    "pagine",
    "pagina",
    "pagInizio"
})
@XmlRootElement(name = "output")
public class Output {

    @XmlElement(required = true)
    protected String typeFileOutput;
    @XmlElement(required = true)
    protected String path;
    @XmlElement(required = true)
    protected BigInteger cartella;
    @XmlElement(required = true)
    protected Output.Gen gen;
    @XmlElement(required = true)
    protected Output.Bib bib;
    @XmlElement(required = true)
    protected Output.Xml xml;
    @XmlElement(required = true)
    protected Output.Images images;
    protected Output.Pagine pagine;
    protected BigInteger pagina;
    protected BigInteger pagInizio;

    /**
     * Gets the value of the typeFileOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeFileOutput() {
        return typeFileOutput;
    }

    /**
     * Sets the value of the typeFileOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeFileOutput(String value) {
        this.typeFileOutput = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the cartella property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCartella() {
        return cartella;
    }

    /**
     * Sets the value of the cartella property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCartella(BigInteger value) {
        this.cartella = value;
    }

    /**
     * Gets the value of the gen property.
     * 
     * @return
     *     possible object is
     *     {@link Output.Gen }
     *     
     */
    public Output.Gen getGen() {
        return gen;
    }

    /**
     * Sets the value of the gen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Output.Gen }
     *     
     */
    public void setGen(Output.Gen value) {
        this.gen = value;
    }

    /**
     * Gets the value of the bib property.
     * 
     * @return
     *     possible object is
     *     {@link Output.Bib }
     *     
     */
    public Output.Bib getBib() {
        return bib;
    }

    /**
     * Sets the value of the bib property.
     * 
     * @param value
     *     allowed object is
     *     {@link Output.Bib }
     *     
     */
    public void setBib(Output.Bib value) {
        this.bib = value;
    }

    /**
     * Gets the value of the xml property.
     * 
     * @return
     *     possible object is
     *     {@link Output.Xml }
     *     
     */
    public Output.Xml getXml() {
        return xml;
    }

    /**
     * Sets the value of the xml property.
     * 
     * @param value
     *     allowed object is
     *     {@link Output.Xml }
     *     
     */
    public void setXml(Output.Xml value) {
        this.xml = value;
    }

    /**
     * Gets the value of the images property.
     * 
     * @return
     *     possible object is
     *     {@link Output.Images }
     *     
     */
    public Output.Images getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     * 
     * @param value
     *     allowed object is
     *     {@link Output.Images }
     *     
     */
    public void setImages(Output.Images value) {
        this.images = value;
    }

    /**
     * Gets the value of the pagine property.
     * 
     * @return
     *     possible object is
     *     {@link Output.Pagine }
     *     
     */
    public Output.Pagine getPagine() {
        return pagine;
    }

    /**
     * Sets the value of the pagine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Output.Pagine }
     *     
     */
    public void setPagine(Output.Pagine value) {
        this.pagine = value;
    }

    /**
     * Gets the value of the pagina property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPagina() {
        return pagina;
    }

    /**
     * Sets the value of the pagina property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPagina(BigInteger value) {
        this.pagina = value;
    }

    /**
     * Gets the value of the pagInizio property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPagInizio() {
        return pagInizio;
    }

    /**
     * Sets the value of the pagInizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPagInizio(BigInteger value) {
        this.pagInizio = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="key">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;sequence maxOccurs="unbounded">
     *           &lt;element name="campo">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati" maxOccurs="unbounded"/>
     *                   &lt;/sequence>
     *                   &lt;attribute name="tipo" use="required">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="bid"/>
     *                         &lt;enumeration value="natura"/>
     *                         &lt;enumeration value="autore"/>
     *                         &lt;enumeration value="titolo"/>
     *                         &lt;enumeration value="pubblicazione"/>
     *                         &lt;enumeration value="biblioteca"/>
     *                         &lt;enumeration value="collocazione"/>
     *                         &lt;enumeration value="inventario"/>
     *                         &lt;enumeration value="annata"/>
     *                         &lt;enumeration value="numero"/>
     *                         &lt;enumeration value="giorno"/>
     *                         &lt;enumeration value="mese"/>
     *                         &lt;enumeration value="anno"/>
     *                         &lt;enumeration value="cronaca"/>
     *                         &lt;enumeration value="year"/>
     *                         &lt;enumeration value="issue"/>
     *                         &lt;enumeration value="stpiece_per"/>
     *                         &lt;enumeration value="part_number"/>
     *                         &lt;enumeration value="part_name"/>
     *                         &lt;enumeration value="stpiece_vol"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/attribute>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/sequence>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "key",
        "campo"
    })
    public static class Bib {

        @XmlElement(required = true)
        protected Output.Bib.Key key;
        @XmlElement(required = true)
        protected List<Output.Bib.Campo> campo;

        /**
         * Gets the value of the key property.
         * 
         * @return
         *     possible object is
         *     {@link Output.Bib.Key }
         *     
         */
        public Output.Bib.Key getKey() {
            return key;
        }

        /**
         * Sets the value of the key property.
         * 
         * @param value
         *     allowed object is
         *     {@link Output.Bib.Key }
         *     
         */
        public void setKey(Output.Bib.Key value) {
            this.key = value;
        }

        /**
         * Gets the value of the campo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the campo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCampo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Output.Bib.Campo }
         * 
         * 
         */
        public List<Output.Bib.Campo> getCampo() {
            if (campo == null) {
                campo = new ArrayList<Output.Bib.Campo>();
            }
            return this.campo;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attribute name="tipo" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="bid"/>
         *             &lt;enumeration value="natura"/>
         *             &lt;enumeration value="autore"/>
         *             &lt;enumeration value="titolo"/>
         *             &lt;enumeration value="pubblicazione"/>
         *             &lt;enumeration value="biblioteca"/>
         *             &lt;enumeration value="collocazione"/>
         *             &lt;enumeration value="inventario"/>
         *             &lt;enumeration value="annata"/>
         *             &lt;enumeration value="numero"/>
         *             &lt;enumeration value="giorno"/>
         *             &lt;enumeration value="mese"/>
         *             &lt;enumeration value="anno"/>
         *             &lt;enumeration value="cronaca"/>
         *             &lt;enumeration value="year"/>
         *             &lt;enumeration value="issue"/>
         *             &lt;enumeration value="stpiece_per"/>
         *             &lt;enumeration value="part_number"/>
         *             &lt;enumeration value="part_name"/>
         *             &lt;enumeration value="stpiece_vol"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dati"
        })
        public static class Campo {

            @XmlElement(required = true)
            protected List<Dati> dati;
            @XmlAttribute(name = "tipo", required = true)
            protected String tipo;

            /**
             * Gets the value of the dati property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dati property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDati().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Dati }
             * 
             * 
             */
            public List<Dati> getDati() {
                if (dati == null) {
                    dati = new ArrayList<Dati>();
                }
                return this.dati;
            }

            /**
             * Gets the value of the tipo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipo() {
                return tipo;
            }

            /**
             * Sets the value of the tipo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipo(String value) {
                this.tipo = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dati"
        })
        public static class Key {

            @XmlElement(required = true)
            protected List<Dati> dati;

            /**
             * Gets the value of the dati property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dati property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDati().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Dati }
             * 
             * 
             */
            public List<Dati> getDati() {
                if (dati == null) {
                    dati = new ArrayList<Dati>();
                }
                return this.dati;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stprog" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="collection" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="agency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="access_rights">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;pattern value="0"/>
     *               &lt;pattern value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="completeness">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;pattern value="0"/>
     *               &lt;pattern value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stprog",
        "collection",
        "agency",
        "accessRights",
        "completeness"
    })
    public static class Gen {

        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String stprog;
        @XmlSchemaType(name = "anyURI")
        protected String collection;
        @XmlElement(required = true)
        protected String agency;
        @XmlElement(name = "access_rights", required = true, defaultValue = "1")
        protected BigInteger accessRights;
        @XmlElement(required = true, defaultValue = "0")
        protected BigInteger completeness;

        /**
         * Gets the value of the stprog property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStprog() {
            return stprog;
        }

        /**
         * Sets the value of the stprog property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStprog(String value) {
            this.stprog = value;
        }

        /**
         * Gets the value of the collection property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCollection() {
            return collection;
        }

        /**
         * Sets the value of the collection property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCollection(String value) {
            this.collection = value;
        }

        /**
         * Gets the value of the agency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAgency() {
            return agency;
        }

        /**
         * Sets the value of the agency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAgency(String value) {
            this.agency = value;
        }

        /**
         * Gets the value of the accessRights property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAccessRights() {
            return accessRights;
        }

        /**
         * Sets the value of the accessRights property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAccessRights(BigInteger value) {
            this.accessRights = value;
        }

        /**
         * Gets the value of the completeness property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCompleteness() {
            return completeness;
        }

        /**
         * Sets the value of the completeness property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCompleteness(BigInteger value) {
            this.completeness = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nomenclatura">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="image" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.randalf.mx/converterXls2Xml}path"/>
     *                   &lt;element ref="{http://www.randalf.mx/converterXls2Xml}formatoImg"/>
     *                   &lt;element name="usage">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="1"/>
     *                         &lt;enumeration value="2"/>
     *                         &lt;enumeration value="3"/>
     *                         &lt;enumeration value="4"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="converter" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ppi" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="quality" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="resize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nomenclatura",
        "image"
    })
    public static class Images {

        @XmlElement(required = true)
        protected Output.Images.Nomenclatura nomenclatura;
        @XmlElement(required = true)
        protected List<Output.Images.Image> image;

        /**
         * Gets the value of the nomenclatura property.
         * 
         * @return
         *     possible object is
         *     {@link Output.Images.Nomenclatura }
         *     
         */
        public Output.Images.Nomenclatura getNomenclatura() {
            return nomenclatura;
        }

        /**
         * Sets the value of the nomenclatura property.
         * 
         * @param value
         *     allowed object is
         *     {@link Output.Images.Nomenclatura }
         *     
         */
        public void setNomenclatura(Output.Images.Nomenclatura value) {
            this.nomenclatura = value;
        }

        /**
         * Gets the value of the image property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the image property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Output.Images.Image }
         * 
         * 
         */
        public List<Output.Images.Image> getImage() {
            if (image == null) {
                image = new ArrayList<Output.Images.Image>();
            }
            return this.image;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.randalf.mx/converterXls2Xml}path"/>
         *         &lt;element ref="{http://www.randalf.mx/converterXls2Xml}formatoImg"/>
         *         &lt;element name="usage">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="1"/>
         *               &lt;enumeration value="2"/>
         *               &lt;enumeration value="3"/>
         *               &lt;enumeration value="4"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="converter" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ppi" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="quality" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="resize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "path",
            "formatoImg",
            "usage",
            "converter"
        })
        public static class Image {

            @XmlElement(required = true)
            protected String path;
            @XmlElement(required = true)
            protected FormatoImg formatoImg;
            @XmlElement(required = true)
            protected String usage;
            protected Output.Images.Image.Converter converter;

            /**
             * Gets the value of the path property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPath() {
                return path;
            }

            /**
             * Sets the value of the path property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPath(String value) {
                this.path = value;
            }

            /**
             * Gets the value of the formatoImg property.
             * 
             * @return
             *     possible object is
             *     {@link FormatoImg }
             *     
             */
            public FormatoImg getFormatoImg() {
                return formatoImg;
            }

            /**
             * Sets the value of the formatoImg property.
             * 
             * @param value
             *     allowed object is
             *     {@link FormatoImg }
             *     
             */
            public void setFormatoImg(FormatoImg value) {
                this.formatoImg = value;
            }

            /**
             * Gets the value of the usage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUsage() {
                return usage;
            }

            /**
             * Sets the value of the usage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUsage(String value) {
                this.usage = value;
            }

            /**
             * Gets the value of the converter property.
             * 
             * @return
             *     possible object is
             *     {@link Output.Images.Image.Converter }
             *     
             */
            public Output.Images.Image.Converter getConverter() {
                return converter;
            }

            /**
             * Sets the value of the converter property.
             * 
             * @param value
             *     allowed object is
             *     {@link Output.Images.Image.Converter }
             *     
             */
            public void setConverter(Output.Images.Image.Converter value) {
                this.converter = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ppi" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="quality" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="resize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "ppi",
                "width",
                "height",
                "quality",
                "resize"
            })
            public static class Converter {

                protected int ppi;
                @XmlElement(defaultValue = "0")
                protected int width;
                @XmlElement(defaultValue = "0")
                protected int height;
                @XmlElement(defaultValue = "60")
                protected double quality;
                protected Integer resize;

                /**
                 * Gets the value of the ppi property.
                 * 
                 */
                public int getPpi() {
                    return ppi;
                }

                /**
                 * Sets the value of the ppi property.
                 * 
                 */
                public void setPpi(int value) {
                    this.ppi = value;
                }

                /**
                 * Gets the value of the width property.
                 * 
                 */
                public int getWidth() {
                    return width;
                }

                /**
                 * Sets the value of the width property.
                 * 
                 */
                public void setWidth(int value) {
                    this.width = value;
                }

                /**
                 * Gets the value of the height property.
                 * 
                 */
                public int getHeight() {
                    return height;
                }

                /**
                 * Sets the value of the height property.
                 * 
                 */
                public void setHeight(int value) {
                    this.height = value;
                }

                /**
                 * Gets the value of the quality property.
                 * 
                 */
                public double getQuality() {
                    return quality;
                }

                /**
                 * Sets the value of the quality property.
                 * 
                 */
                public void setQuality(double value) {
                    this.quality = value;
                }

                /**
                 * Gets the value of the resize property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getResize() {
                    return resize;
                }

                /**
                 * Sets the value of the resize property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setResize(Integer value) {
                    this.resize = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dati"
        })
        public static class Nomenclatura {

            @XmlElement(required = true)
            protected List<Dati> dati;

            /**
             * Gets the value of the dati property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dati property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDati().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Dati }
             * 
             * 
             */
            public List<Dati> getDati() {
                if (dati == null) {
                    dati = new ArrayList<Dati>();
                }
                return this.dati;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="stop" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "start",
        "stop"
    })
    public static class Pagine {

        @XmlElement(required = true)
        protected BigInteger start;
        @XmlElement(required = true)
        protected BigInteger stop;

        /**
         * Gets the value of the start property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getStart() {
            return start;
        }

        /**
         * Sets the value of the start property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setStart(BigInteger value) {
            this.start = value;
        }

        /**
         * Gets the value of the stop property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getStop() {
            return stop;
        }

        /**
         * Sets the value of the stop property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setStop(BigInteger value) {
            this.stop = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="folder" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="fileName">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="extension" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "folder",
        "fileName"
    })
    public static class Xml {

        @XmlElement(required = true)
        protected List<Output.Xml.Folder> folder;
        @XmlElement(required = true)
        protected Output.Xml.FileName fileName;

        /**
         * Gets the value of the folder property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the folder property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFolder().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Output.Xml.Folder }
         * 
         * 
         */
        public List<Output.Xml.Folder> getFolder() {
            if (folder == null) {
                folder = new ArrayList<Output.Xml.Folder>();
            }
            return this.folder;
        }

        /**
         * Gets the value of the fileName property.
         * 
         * @return
         *     possible object is
         *     {@link Output.Xml.FileName }
         *     
         */
        public Output.Xml.FileName getFileName() {
            return fileName;
        }

        /**
         * Sets the value of the fileName property.
         * 
         * @param value
         *     allowed object is
         *     {@link Output.Xml.FileName }
         *     
         */
        public void setFileName(Output.Xml.FileName value) {
            this.fileName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati"/>
         *       &lt;/sequence>
         *       &lt;attribute name="extension" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dati"
        })
        public static class FileName {

            @XmlElement(required = true)
            protected List<Dati> dati;
            @XmlAttribute(name = "extension", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String extension;

            /**
             * Gets the value of the dati property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dati property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDati().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Dati }
             * 
             * 
             */
            public List<Dati> getDati() {
                if (dati == null) {
                    dati = new ArrayList<Dati>();
                }
                return this.dati;
            }

            /**
             * Gets the value of the extension property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExtension() {
                return extension;
            }

            /**
             * Sets the value of the extension property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExtension(String value) {
                this.extension = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element ref="{http://www.randalf.mx/converterXls2Xml}dati"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dati"
        })
        public static class Folder {

            @XmlElement(required = true)
            protected List<Dati> dati;

            /**
             * Gets the value of the dati property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dati property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDati().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Dati }
             * 
             * 
             */
            public List<Dati> getDati() {
                if (dati == null) {
                    dati = new ArrayList<Dati>();
                }
                return this.dati;
            }

        }

    }

}
