//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 05:57:43 PM CET 
//


package mx.randalf.converterxls2xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pathImageMagick" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nThread" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tSleep" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tSleepClosed" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pathImageMagick",
    "nThread",
    "tSleep",
    "tSleepClosed"
})
@XmlRootElement(name = "parameter")
public class Parameter {

    @XmlElement(required = true)
    protected String pathImageMagick;
    @XmlElement(required = true, defaultValue = "10")
    protected BigInteger nThread;
    @XmlElement(required = true, defaultValue = "1000")
    protected BigInteger tSleep;
    @XmlElement(defaultValue = "60000")
    protected BigInteger tSleepClosed;

    /**
     * Gets the value of the pathImageMagick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathImageMagick() {
        return pathImageMagick;
    }

    /**
     * Sets the value of the pathImageMagick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathImageMagick(String value) {
        this.pathImageMagick = value;
    }

    /**
     * Gets the value of the nThread property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNThread() {
        return nThread;
    }

    /**
     * Sets the value of the nThread property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNThread(BigInteger value) {
        this.nThread = value;
    }

    /**
     * Gets the value of the tSleep property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTSleep() {
        return tSleep;
    }

    /**
     * Sets the value of the tSleep property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTSleep(BigInteger value) {
        this.tSleep = value;
    }

    /**
     * Gets the value of the tSleepClosed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTSleepClosed() {
        return tSleepClosed;
    }

    /**
     * Sets the value of the tSleepClosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTSleepClosed(BigInteger value) {
        this.tSleepClosed = value;
    }

}
